connection: &connection
  adapter: postgresql
  encoding: unicode
  host:     localhost
  pool: 5
  username: dszromik
  password: dszromik

development:
  <<: *connection
  database: bookmark_development

test: &test
  <<: *connection
  database: bookmark_test
