# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23cb5d023f30f8c85196bae4089678fbe865a507c7677bcb1c82cb8faf0239b80d72692d6adc31080d4717b77c200e6089a1de75f64e85449b16b803733c4ce4

test:
  secret_key_base: eb557764f5e06b356da95ac54b23155daa700727ea518d2f431d57eec9b5a097191a563b9fe8d85760c17071b6e871ee02ba88a2d498ee246b68e1824e1cbe97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
